export const fileTypes = {
  mp4: 'Video',
  mp3: 'Audio',
  pdf: 'PDF',
  jpg: 'Image',
  jpeg: 'Image',
  png: 'Image',
  jfif: 'Image',
  gif: 'Image',
  webp: 'Image',
  ico: 'Image',
  svg: 'Image',
  docx: 'Word',
  xlxs: 'Excel',
  txt: 'Text',
  pptx: 'Powerpoint',
  zip: 'Compressed Archive',
  any: 'Unknown Type',
};
